[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Context-Aware-Jenkins-Job-Transfers-Documentation"
authors = [{name = "Joel Thomas Chacko", email = "joelkariyalil@gmail.com"}]
dynamic = ["version", "description"]
